AWSTemplateFormatVersion: '2010-09-09'
Description: Creating an EC2 instance with SSH access

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0   # Replace with your IP range in production for security
        
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: CPl                # Replace with your EC2 key pair
      ImageId: ami-01b6d88af12965bb6     # Replace with the correct AMI ID for your region
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: ec2-user