AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket with Versioning Enabled

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket
      VersioningConfiguration:
        Status: Enabled
